name: C++ CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ pip
          sudo pip instal conan

      - name: Configure Conan
        run: conan install . --output-folder=build --build=missing --settings=build_type=Debug

      - name: Configure CMake
        run: cmake .

      - name: Build project
        run: cmake --build build

      - name: Run tests
        working-directory: build
        run: ctest --output-on-failure --build-config Debug